name: CampusX Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # =========================
      # CHECKOUT
      # =========================

      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # SETUP FLUTTER
      # =========================

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # =========================
      # VERIFY FLUTTER
      # =========================

      - name: Flutter Version
        run: flutter --version

      - name: Flutter Doctor
        run: flutter doctor -v

      # =========================
      # INSTALL DEPENDENCIES
      # =========================

      - name: Install dependencies
        run: flutter pub get

      # =========================
      # ANDROID APK
      # =========================

      - name: Build Android APK
        run: flutter build apk --release --dart-define-from-file=env.json

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: CampusX-Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk

      # =========================
      # WINDOWS BUILD
      # =========================

      - name: Build Windows
        run: flutter build windows --release --dart-define-from-file=env.json

      # =========================
      # INSTALL INNO SETUP
      # =========================

      - name: Install Inno Setup
        run: choco install innosetup -y

      # =========================
      # BUILD WINDOWS INSTALLER
      # =========================

      - name: Build Windows Installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer\campusx.iss"

      # =========================
      # UPLOAD WINDOWS INSTALLER
      # =========================

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: CampusX-Windows-Installer
          path: installer/Output/*.exe

      # =========================
      # UPLOAD WINDOWS PORTABLE
      # =========================

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: CampusX-Windows
          path: build/windows/x64/runner/Release/
